require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    # 自動生成系は除外
    - bin/{brakeman,bundle,dev,jobs,kamal,rails,rake,rubocop,thrust}
    - db/{,cache_,queue_}schema.rb

Style/AsciiComments:
  Enabled: false # 日本語のコメントを許可

Style/Documentation:
  Enabled: false # しばらくそんな大規模にならないので無効化。でかくなったら考える

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]

Metrics/AbcSize:
  CountRepeatedAttributes: false
