# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'kamal', require: false
gem 'rails', '~> 8.0.0'
gem 'solid_cache'
gem 'solid_queue'
gem 'thruster', require: false

gem 'puma'
gem 'sqlite3'

group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', require: 'debug/prelude'

  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end
